name: Playit

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Playit
        run: |
          wget https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3
          chmod 777 playit-0.9.3
          nohup ./playit-0.9.3 > playint.txt
          sleep 10

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE }}

      - name: Setup 
        run: |
          rclone copy playint.txt Drive:
          sleep 300
          rclone copy playit.toml Drive:

