name: Playit

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE }}

      - name: RUN Playit
        run: |
          rclone copy Drive:playit .
          rclone copy Drive:playit.toml .
          chmod 777 playit
          nohup ./playit &

      - name: Setup McServ
        run: |
          rclone copy Drive:mcserv.sh .
          bash mcserv.sh

      - name: Run McServ
        run: |
           chmod +x bedrock_server
           cd mc
           timeout 4h ./bedrock_server

      - name: Post Worlds
        if: always()
        run: |
          sleep 5
          pkill -9 bedrock_server
          cd mc/worlds && zip -r1 map.zip *
          rclone copy map.zip Drive:mc
