name: McPro

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: map.ovpn

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE }}

      - name: Setup McServ
        run: |
          rclone copy Drive:mcserv.sh .
          bash mcserv.sh

      - name: Run McServ
        run: |
           cd mc
           chmod +x bedrock_server
           timeout 4h ./bedrock_server

      - name: Post Worlds
        if: always()
        run: |
          cd mc/worlds && zip -r1 map.zip *
          rclone copy map.zip Drive:mc
