name: Proxy-ply

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install PlayIt
        run: |
          mkdir ply && cd ply && echo ${{ secrets.THIS_PLY }} > this.txt && wget --no-check-certificate https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3 && chmod +x * && base64 -d this.txt > playit.toml

      - name: Up Docker
        run: |
          docker run -d -p "6080:3128/tcp" ghcr.io/tarampampam/3proxy:latest 
          timeout 12600 ./playit-0.9.3
