name: NoSSH-Ply

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install PlayIt
        run: |
          mkdir ply && cd ply && echo ${{ secrets.THIS_PLY }} > this.txt && wget --no-check-certificate https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3 && chmod +x * && base64 -d this.txt > playit.toml

      - name: Set UP NOW
        run: |
          docker run -d --publish=2222:22 --env ROOT_PASSWORD=poop hermsi/alpine-sshd
          docker run -p 6080:5900 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc

      - name: Go to playit
        run: cd ply && timeout 5h ./playit-0.9.3
