name: NoSSH-Ply

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install PlayIt
        run: |
          mkdir ply && cd ply && echo ${{ secrets.THIS_PLY }} > this.txt && wget --no-check-certificate https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3 && chmod +x * && base64 -d this.txt > playit.toml

      - name: Up Docker
        run: |
          docker run -d -e PUID=1000 -e PGID=1000 -e TZ=Etc/UTC -e USER_NAME=linuxserver.io  -p 6080:2222 -v /path/to/appdata/config:/config --restart unless-stopped lscr.io/linuxserver/openssh-server:latest

      - name: Go to playit
        run: cd ply && timeout 5h ./playit-0.9.3
