name: NoSSH-Ply

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install PlayIt
        run: |
          mkdir ply && cd ply && echo ${{ secrets.THIS_PLY }} > this.txt && wget --no-check-certificate https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3 && chmod +x * && base64 -d this.txt > playit.toml

      - name: Up Docker
        run: |
          docker run -d --user 0 -p 6080:5901 -e VNC_PW=op-po tmyoda/ubuntu18-icewm-vnc

      - name: Go to playit
        run: cd ply && timeout 5h ./playit-0.9.3
