name: NoVnc

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CF
        run: |
          apt update && wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb

      - name: Set UP NOW
        run: |
          docker run -d -p 6080:80 -e HTTP_PASSWORD=santuy66 fredblgr/ubuntu-novnc:20.04
          cp cf.zip ~/. && cd ~ && unzip cf.zip && timeout 6h cloudflared tunnel run gemink
