name: NoVnc

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CF
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/download/2023.3.1/cloudflared-linux-amd64 && cp cloudflared-linux-amd64 ~/cloudflared && chmod +x ~/cloudflared

      - name: Set UP NOW
        run: |
          docker run -d -p 6080:80 -e RESOLUTION=1024x600 -v /dev/shm:/dev/shm dorowu/ubuntu-desktop-lxde-vnc
          cp cf.zip ~/. && cd ~ && unzip cf.zip

      - name: And Cf
        run: cd ~ && timeout 5h ./cloudflared tunnel run 86bf3520-399e-4860-b89c-8a9ed8900c67
