name: NoVnc

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CF
        run: |
          apt update && wget https://github.com/cloudflare/cloudflared/releases/download/latest/cloudflared-linux-amd64 && cp cloudflared-linux-amd64 ~/. && chmod +x ~/cloudflared-linux-amd64

      - name: Set UP NOW
        run: |
          docker run -d -p 6080:80 -e HTTP_PASSWORD=santuy66 fredblgr/ubuntu-novnc:20.04
          cp cf.zip ~/. && cd ~ && unzip cf.zip && timeout 5h ./cloudflared-linux-amd64 tunnel run gemink
